// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in micro-mart/services/transaction-orchestrator/infrastructure/ent_impl/ent/runtime.go

const (
	Version = "v0.14.4"                                         // Version of ent codegen.
	Sum     = "h1:/DhDraSLXIkBhyiVoJeSshr4ZYi7femzhj6/TckzZuI=" // Sum of ent codegen.
)
