version: '3.8'
name: go-test-mm

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwaszx1325
      POSTGRES_DB: mirco_mart_DB
    ports:
      - "5434:5432"
    volumes:
      - ./init-multiple-db.sql:/docker-entrypoint-initdb.d/init-multiple-db.sql
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "root" ]
    networks:
      - backend

  jaeger:
    image: jaegertracing/all-in-one:1.46
    container_name: jaeger
    restart: unless-stopped
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - backend

networks:
  backend:
