CREATE DATABASE user_db;
CREATE DATABASE order_db;
CREATE DATABASE product_db;
CREATE DATABASE transaction_db;


-- 想要新增使用者可以用下方方式新增
-- CREATE USER xiu WITH PASSWORD 'qwaszx1325' SUPERUSER;
-- GRANT ALL PRIVILEGES ON DATABASE mirco_mart_DB TO xiu;
-- GRANT ALL PRIVILEGES ON DATABASE user_db TO xiu;
-- GRANT ALL PRIVILEGES ON DATABASE order_db TO xiu;
-- GRANT ALL PRIVILEGES ON DATABASE product_db TO xiu;